spring:
  application:
    name: final-komp

  datasource:
    url: jdbc:postgresql://localhost:5432/ThreeChTsixMarchProjectDB
    username: azat
    password: azat07
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 1010

  jwt:
    secret: my-super-secret-jwt-key-for-final-project-very-long
    expiration: 86400000